//! Cryptographic security, password hashing, token generation, and authentication extraction.
//!
//! # Cryptographic Invariants
//! - **Password Hashing**: Passwords are hashed exclusively using the Argon2id algorithm
//!   with cryptographically secure random salts generated by [`rand_core::OsRng`].
//! - **Session Tokens**: Opaque 256-bit (32-byte) cryptographically secure pseudorandom
//!   tokens encoded as 64-character lowercase hexadecimal strings.
//! - **Dual-Channel Authentication**: The [`AuthUser`] extractor transparently resolves
//!   sessions from either inbound HTTP cookies (`cosave_session`) or standard HTTP
//!   `Authorization: Bearer <token>` headers.
//! - **Cookie Hygiene**: Session cookies are strictly configured with `HttpOnly(true)`,
//!   `SameSite(Lax)`, `Path("/")`, and a 30-day lifetime window.

use argon2::{
    password_hash::{rand_core::OsRng, PasswordHash, PasswordHasher, PasswordVerifier, SaltString},
    Argon2,
};
use axum::{
    extract::{FromRef, FromRequestParts},
    http::{header::AUTHORIZATION, request::Parts},
};
use axum_extra::extract::{
    cookie::{Cookie, SameSite},
    CookieJar,
};
use rand::RngCore;
use time::Duration;

use crate::core::{now_epoch_secs, AppError, AppState};

use super::db;
use super::error::AuthError;
use super::models::User;

/// Name of the HTTP cookie used to transport the active session token.
pub(super) const SESSION_COOKIE_NAME: &str = "cosave_session";

/// Duration in seconds for which an issued session token remains valid (30 days).
pub(super) const SESSION_DURATION_SECS: i64 = 30 * 24 * 3600;

/// Hashes a plaintext password using Argon2id with a cryptographically secure random salt.
///
/// # Ingress
/// - `password`: Plaintext password slice to hash.
///
/// # Returns
/// - `Ok(String)` containing the encoded Argon2id PHC string.
///
/// # Errors
/// Returns [`AppError::ShouldNotBeHappening`] with action `AUTH.HASH_PASSWORD.GENERATE` if Argon2id hashing fails.
pub(super) fn hash_password(password: &str) -> Result<String, AppError> {
    let salt = SaltString::generate(&mut OsRng);
    let argon2 = Argon2::default();
    argon2
        .hash_password(password.as_bytes(), &salt)
        .map(|h| h.to_string())
        .map_err(|e| AppError::ShouldNotBeHappening {
            action: "AUTH.HASH_PASSWORD.GENERATE",
            reason: format!("argon2 hashing failed: {e}"),
        })
}

/// Verifies a plaintext password against an Argon2id PHC hash string.
///
/// Executes constant-time password verification.
///
/// # Ingress
/// - `password`: Inbound candidate plaintext password slice.
/// - `hash`: Stored Argon2id PHC hash string from the database.
///
/// # Returns
/// - `true` if the password matches the hash.
/// - `false` if the hash is malformed or the password does not match.
pub(super) fn verify_password(password: &str, hash: &str) -> bool {
    let parsed_hash = match PasswordHash::new(hash) {
        Ok(h) => h,
        Err(_) => return false,
    };
    Argon2::default()
        .verify_password(password.as_bytes(), &parsed_hash)
        .is_ok()
}

/// Generates a cryptographically secure random 256-bit hexadecimal session token.
///
/// Uses `rand::thread_rng` to draw 32 random bytes, formatted as a 64-character lowercase hex string.
pub(super) fn generate_token() -> String {
    let mut bytes = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut bytes);
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Creates an `HttpOnly`, `SameSite=Lax`, `Path="/" session cookie with a 30-day lifetime.
///
/// # Ingress
/// - `token`: The active session token string to embed in the cookie.
pub(super) fn create_session_cookie(token: String) -> Cookie<'static> {
    let mut cookie = Cookie::new(SESSION_COOKIE_NAME, token);
    cookie.set_path("/");
    cookie.set_http_only(true);
    cookie.set_same_site(SameSite::Lax);
    cookie.set_max_age(Some(Duration::seconds(SESSION_DURATION_SECS)));
    cookie
}

/// Creates an expired tombstone cookie to clear the active session on logout.
///
/// Sets `Max-Age=0` to instruct the client browser to immediately purge the cookie.
pub(super) fn remove_session_cookie() -> Cookie<'static> {
    let mut cookie = Cookie::new(SESSION_COOKIE_NAME, "");
    cookie.set_path("/");
    cookie.set_http_only(true);
    cookie.set_same_site(SameSite::Lax);
    cookie.set_max_age(Some(Duration::seconds(0)));
    cookie
}

/// Axum request extractor that resolves and verifies an authenticated session.
///
/// Extracts the session token from either:
/// 1. The `cosave_session` cookie in the request's [`CookieJar`].
/// 2. An `Authorization: Bearer <token>` HTTP header.
///
/// Queries the database to confirm that the session exists and has not expired.
/// If valid, wraps the authenticated internal [`User`] entity.
#[derive(Debug, Clone)]
pub(crate) struct AuthUser(User);

impl AuthUser {
    /// Returns the unique identifier of the authenticated user (`usr-...`).
    pub(crate) fn user_id(&self) -> &str {
        self.0.id()
    }

    /// Consumes the extractor and returns the wrapped internal [`User`] entity.
    pub(super) fn into_user(self) -> User {
        self.0
    }
}

impl<S> FromRequestParts<S> for AuthUser
where
    AppState: FromRef<S>,
    S: Send + Sync,
{
    type Rejection = AppError;

    /// Resolves the authenticated user from inbound request parts.
    ///
    /// # Extraction Order
    /// 1. Checks for the `cosave_session` cookie in the [`CookieJar`].
    /// 2. If absent, checks for an `Authorization: Bearer <token>` header.
    /// 3. Validates that the token exists in the `sessions` table and `expires_at > now`.
    ///
    /// # Rejections
    /// - Returns [`AuthError::Unauthenticated`] with action `AUTH.EXTRACT_USER.MISSING_TOKEN` if
    ///   neither cookie nor bearer token is provided.
    /// - Returns [`AuthError::Unauthenticated`] with action `AUTH.EXTRACT_USER.VALIDATE_TOKEN` if
    ///   the session is invalid, revoked, or expired.
    async fn from_request_parts(parts: &mut Parts, state: &S) -> Result<Self, Self::Rejection> {
        let app_state = AppState::from_ref(state);
        let jar = CookieJar::from_request_parts(parts, state)
            .await
            .map_err(|_| AppError::ShouldNotBeHappening {
                action: "AUTH.EXTRACT_USER.PARSE_COOKIES",
                reason: "failed parsing cookie jar from request parts".to_string(),
            })?;

        let token = jar
            .get(SESSION_COOKIE_NAME)
            .map(|c| c.value().to_string())
            .or_else(|| {
                parts
                    .headers
                    .get(AUTHORIZATION)
                    .and_then(|h| h.to_str().ok())
                    .and_then(|h| h.strip_prefix("Bearer "))
                    .map(|s| s.trim().to_string())
            });

        let Some(token) = token else {
            return Err(AuthError::Unauthenticated {
                action: "AUTH.EXTRACT_USER.MISSING_TOKEN",
            }
            .into());
        };

        let now = now_epoch_secs();

        let user = db::find_user_by_session_token(app_state.db(), &token, now).await?;

        match user {
            Some(u) => Ok(AuthUser(u)),
            None => Err(AuthError::Unauthenticated {
                action: "AUTH.EXTRACT_USER.VALIDATE_TOKEN",
            }
            .into()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_password_hash_and_verify() {
        let password = "SuperSecretPassword123!";
        let hash = hash_password(password).expect("Hashing failed");
        assert!(verify_password(password, &hash));
        assert!(!verify_password("WrongPassword", &hash));
    }

    #[test]
    fn test_token_generation_length() {
        let token1 = generate_token();
        let token2 = generate_token();
        assert_eq!(token1.len(), 64);
        assert_eq!(token2.len(), 64);
        assert_ne!(token1, token2);
    }
}
